name: Build MUSL Binary

on:
  push:
    branches:
      - main
    tags:
      - v* # Match version tags like v1.0.0
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build MUSL Binary
    runs-on: ubuntu-latest
    container:
      image: rust:alpine

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig git build-base

      - name: Build binary
        env:
          OPENSSL_STATIC: true
          OPENSSL_LIB_DIR: /usr/lib
          OPENSSL_INCLUDE_DIR: /usr/include
        run: |
          # Install target
          rustup target add x86_64-unknown-linux-musl
          # Build with MUSL target
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: xs-musl-binary
          path: target/x86_64-unknown-linux-musl/release/xs
          if-no-files-found: error