name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo:
    if: (github.event_name == 'push' || github.event.pull_request.draft == false)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose

  nix-flake:
    if: (github.event_name == 'push' || github.event.pull_request.draft == false)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set NIX_FIRST_BUILD_UID (macOS only)
      if: runner.os == 'macOS'
      run: echo "NIX_FIRST_BUILD_UID=400" >> $GITHUB_ENV
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Flake check
      run: nix run . -- --version
    - name: Test default dev shell
      run: nix develop --command nu --version
    - name: Test bash dev shell
      run: nix develop .#bash --command bash --version
