name: Latest Prerelease

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-musl:
    name: Build & Publish MUSL Binary
    runs-on: ubuntu-latest
    container:
      image: rust:alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MUSL build dependencies
        run: |
          apk add --no-cache \
            musl-dev \
            openssl-dev \
            openssl-libs-static \
            pkgconfig \
            git \
            build-base

      - name: Build xs for x86_64-unknown-linux-musl
        env:
          OPENSSL_STATIC: true
          OPENSSL_LIB_DIR: /usr/lib
          OPENSSL_INCLUDE_DIR: /usr/include
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Create or update “latest” prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: latest
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload xs binary to “latest”
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          asset_name: xs-musl-x86_64
          asset_path: target/x86_64-unknown-linux-musl/release/xs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
