name: Nix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Flake check
      run: nix run . -- --version
    - name: Test default dev shell
      run: nix develop --command nu --version
    - name: Test bash dev shell
      run: nix develop .#bash --command bash --version
